"""
Generated by Colab, and Original file is located at
    https://colab.research.google.com/drive/1XTbiCHu5_FMwsNWl6qDV8i9PWCAhrI80
"""

"""
ingest.py
---------
Owner: Srijita Nath (Fixed for Docker & UI Integration)

What this file does:
    1. Loads the Facebook Hateful Memes dataset (train.jsonl)
    2. Cleans the meme text (lowercase, remove noise, handle emojis)
    3. Generates sentence embeddings using all-MiniLM-L6-v2
    4. Stores everything into ChromaDB vector database

Input:  data/train.jsonl
Output: ChromaDB collection with 8,500+ embedded meme entries
"""

# ── imports ────────────────────────────────────────────────────────────────
import json
import os
import re

import chromadb
import emoji
import pandas as pd
from sentence_transformers import SentenceTransformer

# ── settings ───────────────────────────────────────────────────────────────
DATA_PATH       = "data/train.jsonl"
COLLECTION_NAME = "memes"
EMBED_MODEL     = "all-MiniLM-L6-v2"
MIN_TEXT_LENGTH = 10


# ── step 1: load data ──────────────────────────────────────────────────────
def load_data(file_path: str) -> pd.DataFrame:
    print(f"\n Loading data from {file_path} ...")

    data = []
    with open(file_path, "r") as f:
        for line in f:
            entry = json.loads(line)
            data.append(entry)

    df = pd.DataFrame(data)
    df = df[["id", "text", "label"]]

    print(f" Loaded {len(df)} entries")
    print(f" Hateful (1): {df['label'].sum()}  |  Not hateful (0): {(df['label']==0).sum()}")

    return df


# ── step 2: clean text ─────────────────────────────────────────────────────
def clean_text(text: str) -> str:
    text = emoji.demojize(text)
    text = text.lower()
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text


def clean_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    print("\n Cleaning text ...")
    df["text"] = df["text"].apply(clean_text)

    before = len(df)
    df = df[df["text"].str.len() >= MIN_TEXT_LENGTH]
    after = len(df)

    print(f" Removed {before - after} entries (too short, under {MIN_TEXT_LENGTH} chars)")
    print(f" Remaining entries: {after}")

    df["dataset"] = "facebook"

    # GitHub repo for citation links
    df["source_url"] = df["id"].apply(
        lambda x: f"https://github.com/bhoomika1909/memerag/blob/main/data/img/{str(x).zfill(5)}.png"
    )

    return df


# ── step 3: store into chromadb ────────────────────────────────────────────
def store_in_chromadb(df: pd.DataFrame) -> None:
    host = os.getenv("CHROMA_HOST", "localhost")
    port = os.getenv("CHROMA_PORT", "8000")
    print(f"\n Connecting to ChromaDB server at {host}:{port} ...")

    client = chromadb.HttpClient(host=host, port=port)

    print(f" Loading embedding model: {EMBED_MODEL} ...")
    embed_model = SentenceTransformer(EMBED_MODEL)

    collection = client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"}
    )

    print(f"\n Embedding and storing {len(df)} entries into ChromaDB ...")
    print(" This will take 10-15 minutes. Please wait...\n")

    batch_size = 100
    total = len(df)

    for start in range(0, total, batch_size):
        batch = df.iloc[start : start + batch_size]

        texts     = batch["text"].tolist()
        ids       = [f"facebook_{row_id}" for row_id in batch["id"].tolist()]
        metadatas = [
            {
                "label"      : int(row["label"]),
                "dataset"    : row["dataset"],
                "source_url" : row["source_url"],
                "meme_id"    : int(row["id"])
            }
            for _, row in batch.iterrows()
        ]

        embeddings = embed_model.encode(texts).tolist()

        collection.add(
            documents  = texts,
            embeddings = embeddings,
            metadatas  = metadatas,
            ids        = ids
        )

        done = min(start + batch_size, total)
        print(f" Progress: {done}/{total} entries stored ({int(done/total*100)}%)")

    print(f"\n Done! {collection.count()} entries stored in ChromaDB network container.")


# ── step 4: verify it worked ───────────────────────────────────────────────
def verify_chromadb() -> None:
    print("\n Running verification test ...")

    host = os.getenv("CHROMA_HOST", "localhost")
    port = os.getenv("CHROMA_PORT", "8000")
    client = chromadb.HttpClient(host=host, port=port)
    collection = client.get_collection(COLLECTION_NAME)
    model      = SentenceTransformer(EMBED_MODEL)

    test_query = "i hate you so much"
    query_embedding = model.encode([test_query]).tolist()

    results = collection.query(
        query_embeddings = query_embedding,
        n_results        = 3,
        include          = ["documents", "metadatas", "distances"]
    )

    print(f"\n Test query: '{test_query}'")
    print(" Top 3 similar memes retrieved:\n")

    for i in range(3):
        text      = results["documents"][0][i]
        label     = results["metadatas"][0][i]["label"]
        url       = results["metadatas"][0][i]["source_url"]
        distance  = results["distances"][0][i]
        label_str = "HATEFUL" if label == 1 else "NOT HATEFUL"

        print(f"  [{i+1}] {label_str}")
        print(f"       Text     : {text}")
        print(f"       Source   : {url}")
        print(f"       Distance : {round(distance, 4)}")
        print()

    print(" Verification complete — ChromaDB is working correctly!\n")


# ── main ─────────────────
if __name__ == "__main__":

    if not os.path.exists(DATA_PATH):
        print(f"\n ERROR: Data file not found at '{DATA_PATH}'")
        print(" Please download train.jsonl and place it in the data/ folder.")
        exit(1)

    df = load_data(DATA_PATH)
    df = clean_dataframe(df)
    store_in_chromadb(df)
    verify_chromadb()

   
    print(" Ingestion complete! You can now run the app.")
    print(" Next step: streamlit run app.py")
